# from .ARSL_env_camera import MicroSwimmerCameraEnv
#from . import game_test_env_only_img
from .old.game_env_dreamer import MicrorobotEnvGameRayWrapped
from .game_env_dreamer_cont import MicrorobotEnvGameRayWrappedCont, MicrorobotEnvContGame
from .game_env_dreamer_rand_freq import MicrorobotEnvContGameFreq, MicrorobotEnvContGameFreqResampled
from .game_env_8_actions import MicrorobotEnvGame8Act, PIEZO_DIRECTIONS8
from .game_env_no_collision import MicrorobotEnvGameNoCollision
from .game_env_by_the_wall import MicrorobotEnvGameByTheWall

from .ARSL_env_camera_dreamer import MicrorobotEnv