Arduino_settings:
  SERIAL_PORT_ARDUINO: "COM5"
  SERIAL_PORT_UBUNUTU: '/dev/ttyACM0'
  BAUDRATE_ARDUINO: 115200

#Action space settings (4*5*5=100 actions)
Action_space_settings:
  NUMBER_PIEZOS: 8
  NUMBER_FREQUENCIES: 1 # in MHz
  NUMBER_AMPLITUDES: 1 # in V
  TOTAL_ACTIONS: 8
  SAFE_STEPS: 10 # 5 for real env
  ENV_SKIP_STEPS: 4
  MAX_AMPLITUDE: 5.0
  MIN_AMPLITUDE: 1.0

#Image processing settings
Image_processing_settings:
  THRESHOLD_VALUE: 100

Reward Settings:
  reward_function: "inverse"
  reward_target_reached: 10
  reward_collision: -2
  reward_step: +0.001  # Needs to be positive! (if using reverse reward function)
  const: -0.01
  substep_reward: 0.03

# Tektronix settings
Tektronix_settings:
  INSTR_DESCRIPTOR: USB0::0x0699::0x034F::C020081::INSTR # USB0::0x0699::0x0353::2222004::INSTR
  DEFAULT_VPP: 8 #in V
  DEFAULT_FREQUENCY: 2.0 #in MHz

Multienv:
  rows: 1
  cols: 1

#Layout
Layout_settings:
  IMG_SIZE: 64
  IMG_DOWNSIZED_SIZE: 64
  IMG_UPSCALED_SIZE: 512

# General environment settings
General_environment_settings:
  TIMEOUT: 200
  COLLISION_TOLERANCE: 0.01
  TARGET_REACHED_TOLERANCE: 1.5
  COLLISION_RESET_TOLERANCE: 3
  MIN_DISTANCE_TO_NEW_TARGET: 0.04 # In relative coordinates 
  MAX_DISTANCE_TARGET_POINT: 0.2 # In relative coordinates
  N_SUBEPISODES: 8 # Number of subepisodes per episode: new target point is chosen every n subepisodes
  VERBOSE: 0 # 0: no prints, 2: general, 4: bubble area debug
  RANDOM_MOVE_PROBABILITY: 0.70
  BUBBLE_RADIUS: 1.5
  MIN_BUBBLE_RADIUS: 0.4
  MEAN_BUBBLE_RADIUS: 0.6
  MAX_BUBBLE_RADIUS: 0.9
  SUBEPISODE_LENGTH: 0  # Number of subepisodes per episode: New target point is chosen every n subepisodes. 0 means that the subepisode length is off

save_path:
  MAIN_PATH: "/home/m4/Documents/Dreamer_Real_Experiments"